// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Safely pull URLs and append timeout strings
const directUrl = env("DIRECT_URL") ? `${env("DIRECT_URL")}&connect_timeout=30` : undefined;
const databaseUrl = env("DATABASE_URL") ? `${env("DATABASE_URL")}&connect_timeout=30` : undefined;

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // Forces Prisma CLI to wait up to 30 seconds for Neon to wake up
    url: directUrl || databaseUrl,
  },
});



